import { useState } from 'react';
import { Share2, Mail, Link2, Facebook, MessageCircle, Download, Loader2, Lock } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from '@/components/ui/dropdown-menu';
import { toast } from '@/hooks/use-toast';
import { NumerologyResult } from '@/hooks/useNumerology';
import { jsPDF } from 'jspdf';

interface ShareResultsProps {
  result: NumerologyResult;
  name: string;
  system: 'pythagorean' | 'chaldean';
  canDownload: boolean;
  canShare: boolean;
  isPremium: boolean;
  onDownload: () => void;
  onShare: () => void;
  onUpgradeClick: () => void;
}

const numberMeanings: Record<number, { title: string; description: string }> = {
  1: { title: "The Leader", description: "Independence, originality, ambition" },
  2: { title: "The Diplomat", description: "Cooperation, sensitivity, balance" },
  3: { title: "The Creative", description: "Expression, imagination, joy" },
  4: { title: "The Builder", description: "Stability, discipline, hard work" },
  5: { title: "The Adventurer", description: "Freedom, change, versatility" },
  6: { title: "The Nurturer", description: "Responsibility, love, harmony" },
  7: { title: "The Seeker", description: "Wisdom, spirituality, introspection" },
  8: { title: "The Powerhouse", description: "Achievement, abundance, authority" },
  9: { title: "The Humanitarian", description: "Compassion, universal love, wisdom" },
  11: { title: "Master Intuitive", description: "Spiritual insight, enlightenment" },
  22: { title: "Master Builder", description: "Turning dreams into reality" },
  33: { title: "Master Teacher", description: "Spiritual healing, compassion" },
};

export default function ShareResults({
  result,
  name,
  system,
  canDownload,
  canShare,
  isPremium,
  onDownload,
  onShare,
  onUpgradeClick,
}: ShareResultsProps) {
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  const generatePdfContent = () => {
    const systemName = system === 'pythagorean' ? 'Pythagorean' : 'Chaldean';
    
    const getMeaning = (num: number) => numberMeanings[num] || { title: "Unique", description: "A special vibration" };
    
    return {
      title: `Numerology Reading for ${name}`,
      system: systemName,
      lifePath: {
        number: result.lifePath,
        meaning: getMeaning(result.lifePath),
      },
      expression: {
        number: result.expression,
        meaning: getMeaning(result.expression),
      },
      soulUrge: {
        number: result.soulUrge,
        meaning: getMeaning(result.soulUrge),
      },
      personality: {
        number: result.personality,
        meaning: getMeaning(result.personality),
      },
      destiny: {
        number: result.destiny,
        meaning: getMeaning(result.destiny),
      },
    };
  };

  const generatePdf = async () => {
    if (!canDownload) {
      onUpgradeClick();
      return;
    }

    setIsGeneratingPdf(true);
    try {
      const content = generatePdfContent();
      const doc = new jsPDF();
      
      // Title
      doc.setFontSize(24);
      doc.setTextColor(139, 92, 246); // Primary purple
      doc.text('Numerology Reading', 105, 20, { align: 'center' });
      
      doc.setFontSize(14);
      doc.setTextColor(100, 100, 100);
      doc.text(`For: ${name}`, 105, 30, { align: 'center' });
      doc.text(`System: ${content.system}`, 105, 38, { align: 'center' });
      
      let yPos = 55;
      const lineHeight = 25;
      
      const addSection = (title: string, number: number, meaning: { title: string; description: string }) => {
        doc.setFontSize(14);
        doc.setTextColor(139, 92, 246);
        doc.text(`${title}: ${number}`, 20, yPos);
        
        doc.setFontSize(12);
        doc.setTextColor(60, 60, 60);
        doc.text(`${meaning.title}`, 20, yPos + 7);
        
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text(meaning.description, 20, yPos + 14);
        
        yPos += lineHeight;
      };
      
      addSection('Life Path Number', content.lifePath.number, content.lifePath.meaning);
      addSection('Expression Number', content.expression.number, content.expression.meaning);
      addSection('Soul Urge Number', content.soulUrge.number, content.soulUrge.meaning);
      addSection('Personality Number', content.personality.number, content.personality.meaning);
      addSection('Destiny Number', content.destiny.number, content.destiny.meaning);
      
      // Footer
      doc.setFontSize(10);
      doc.setTextColor(150, 150, 150);
      doc.text('Generated by Numerology Hub', 105, 280, { align: 'center' });
      doc.text(new Date().toLocaleDateString(), 105, 287, { align: 'center' });
      
      doc.save(`numerology-reading-${name.toLowerCase().replace(/\s+/g, '-')}.pdf`);
      
      onDownload();
      toast({
        title: 'PDF Downloaded',
        description: 'Your numerology reading has been saved.',
      });
    } catch (error) {
      toast({
        title: 'Download Failed',
        description: 'Unable to generate PDF. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  const getShareText = () => {
    const systemName = system === 'pythagorean' ? 'Pythagorean' : 'Chaldean';
    return `Check out my ${systemName} numerology reading! Life Path: ${result.lifePath}, Expression: ${result.expression}, Soul Urge: ${result.soulUrge}. Get yours at Numerology Hub!`;
  };

  const shareUrl = typeof window !== 'undefined' ? window.location.origin : '';

  const handleShare = (platform: 'whatsapp' | 'facebook' | 'email' | 'copy') => {
    if (!canShare && !isPremium) {
      onUpgradeClick();
      return;
    }

    const text = getShareText();
    
    switch (platform) {
      case 'whatsapp':
        window.open(`https://wa.me/?text=${encodeURIComponent(text + ' ' + shareUrl)}`, '_blank');
        break;
      case 'facebook':
        window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}&quote=${encodeURIComponent(text)}`, '_blank');
        break;
      case 'email':
        window.open(`mailto:?subject=My Numerology Reading&body=${encodeURIComponent(text + '\n\n' + shareUrl)}`, '_blank');
        break;
      case 'copy':
        navigator.clipboard.writeText(text + ' ' + shareUrl);
        toast({
          title: 'Link Copied',
          description: 'Share link copied to clipboard.',
        });
        break;
    }
    
    onShare();
  };

  return (
    <div className="flex gap-2">
      <Button
        variant="secondary"
        size="sm"
        onClick={generatePdf}
        disabled={isGeneratingPdf}
        className="gap-2"
      >
        {isGeneratingPdf ? (
          <Loader2 className="w-4 h-4 animate-spin" />
        ) : !canDownload && !isPremium ? (
          <Lock className="w-4 h-4" />
        ) : (
          <Download className="w-4 h-4" />
        )}
        PDF
      </Button>
      
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="secondary" size="sm" className="gap-2">
            {!canShare && !isPremium ? (
              <Lock className="w-4 h-4" />
            ) : (
              <Share2 className="w-4 h-4" />
            )}
            Share
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-48">
          <DropdownMenuItem onClick={() => handleShare('whatsapp')} className="gap-2 cursor-pointer">
            <MessageCircle className="w-4 h-4" />
            WhatsApp
          </DropdownMenuItem>
          <DropdownMenuItem onClick={() => handleShare('facebook')} className="gap-2 cursor-pointer">
            <Facebook className="w-4 h-4" />
            Facebook
          </DropdownMenuItem>
          <DropdownMenuItem onClick={() => handleShare('email')} className="gap-2 cursor-pointer">
            <Mail className="w-4 h-4" />
            Email
          </DropdownMenuItem>
          <DropdownMenuSeparator />
          <DropdownMenuItem onClick={() => handleShare('copy')} className="gap-2 cursor-pointer">
            <Link2 className="w-4 h-4" />
            Copy Link
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
}
